### ISSUE TITLE
Is it necessary to revisit requirements and use cases?

### ISSUE THREAD

**Issue by DRx3D** [immersive-web/model-element#100]
There have been many rumors that the VisionPro headset may be discontinued [1], [2]. Since much of the original justification for model element was based on requirements of the VisionPro, is it appropriate to take another look at the requirements and use cases to make sure we are still working on the correct problem.

[1] https://www.xrtoday.com/mixed-reality/apple-vision-pro-discontinued-the-rumors-so-far/
[2] https://www.cnet.com/tech/computing/apple-may-stop-vision-pro-production-as-components-pile-up/

**Comment by cabanier** [comment]
> There have been many rumors that the VisionPro headset may be discontinued [1], [2]. Since much of the original justification for model element was based on requirements of the VisionPro, is it appropriate to take another look at the requirements and use cases to make sure we are still working on the correct problem.

Others have expressed interest in adding support for the model tag such as Samsung and Meta.
Also, afaik there is nothing in the proposal that is specific to AVP.

**Comment by toji** [comment]
On top of Rik's comments, I would be hesitant to rely on the linked rumors to imply that Apple is discontinuing Vision**OS**. At the current price point I think Apple probably knew that the Vision Pro wasn't going to be an iPhone-style success, and even the articles you link mention that while the Vision Pro may be winding down production the most likely path forward is for Apple to produce a new headset at a lower price point. Such a headset would be effectively guaranteed to use VisionOS, meaning that most of the use cases Apple has demonstrated in the context of their own device would remain relevant.

As such, unless we hear a direct confirmation from Apple that they are winding down all future VisionOS devices, I don't think this changes our trajectory much. That said, given that the model tag is still in it's formative stage I think it's a healthy thing to continuously re-evaluate it's current direction and use cases to ensure we're building a useful component that adds capabilities to the web platform that couldn't be achived without the new feature!
