### ISSUE TITLE
Means of controlling the shadow

### ISSUE THREAD

**Issue by marcoscaceres** [immersive-web/model-element#48]
There are cases where it may not be desirable to have a shadow being cast, because the shadow can be larger than the viewport in which an object is being show. Also, as the "camera" rotates, the shadow can end up looking weird and exposing the boundary of the `<model>` element.  

For example: 

![Screen Shot 2022-08-09 at 2 25 31 pm](https://user-images.githubusercontent.com/870154/183563942-49a837b5-91ad-4641-a1dc-6ff02a0c4273.png)

It might be good to disable the shadow entirely? Or some other means for developers to express where the light source should be to cast the shadow where they might want.

**Comment by mikkoh** [comment]
A boolean operation of show or hide would be great. I do wonder if there should be a method to adjust the "intensity" of the shadow. In css I believe users often pass in a `rgba` value where `a` adjusts the "intensity" but this in a 3D scenario would produce unrealistic shadows in some cases. I also wonder as technology/performance of 3D rendering improves whether having the ability to adjust the intensity of a shadow becomes moot anyway.

**Comment by marcoscaceres** [comment]
As a start, it might be nice to just disable the shadow... we can start getting into fancier shadow casting/light(s) position/control down the line.

**Comment by AdaRoseCannon** [comment]
I think at least with regards to direction and type of shadow GLTF has
support for providing a light source, although can't dictate whether lights
and objects cast shadow in the model itself I would be surprised if USDZ
didn't also have light support

**Comment by cabanier** [comment]
> As a start, it might be nice to just disable the shadow... we can start getting into fancier shadow casting/light(s) position/control down the line.

The UA can decide if they want to render shadows or not, or how they are rendered.
A UA that actually draws models in 3D is going to want to control the light source and shadow.

**Comment by zachernuk** [comment]
I personally think that no UA should be placing shadows unless an element is out in the world / on the ground, which wasn't the original context for the issue - To talk about that I'd prefer to open a new issue more closely-related to that context.
