### ISSUE TITLE
Constrains on rotation

### ISSUE THREAD

**Issue by marcoscaceres** [immersive-web/model-element#52]
With photogrammetry it's not always possible to capture every angle of an object. This means that a model can be missing details, such as in the situation below: 

<img alt="Underside of a pie" src="https://user-images.githubusercontent.com/870154/184756296-f25e238c-5db3-4359-9a90-301092f6d8fe.png" height="200">

Wondering if it might make sense to constrain the angle(s) in which a user can spin a model when `interactive` is enabled? This could be done with JS and the camera control API, but it might end up being really jerky as the JS code would be fighting the user trying to spin the model. 

Also noting that it may not make sense in an AR context, because a user could simply crouch to look underneath... but that might be ok.

**Comment by zachernuk** [comment]
I feel like this addresses the best approach - JS-based controls could apply additional constraints, but a basic set of controls should provide the most general ability (and for anything more sophisticated, there's Javascript)
