### ISSUE TITLE
polyfill

### ISSUE THREAD

**Issue by trusktr** [immersive-web/model-element#63]
Is there a polyfill for `<model>`? Keith Clark's [`<x-model>`](https://keithclark.co.uk/labs/3d-model-custom-element/examples/tests/) is similar.

I'm curious as to whether it would be more worth it for the browsers to have lower-level 3D elements, for example like [a-frame](https://aframe.io), [LUME](https://github.com/lume/lume) (my fav :D), [x3dom](https://www.x3dom.org), then a GLTF viewing component would be a composition of the lower level elements, much like how a `<input>`'s ShadowRoot contains `<div>`s, etc.

```html
<model>
  <#useragent-shadowroot>
    <mesh has="physical-material" ...>
      ...
    </mesh>
    ...
  </#useragent-shadowroot>
</model>
```

If browsers are going to have standard rendering abilities in order to draw `<model>` elements, we may as well get the benefit of all the pieces as declarative HTML, so that we can manipulate them with Vue/React/Solid/Svelte/etc, and use the power of CSS, f.e.

```html
<mesh>...</mesh>
<mesh>...</mesh>
<mesh>...</mesh>

<style>
  /* give all three meshes the same style */
  mesh {
    geometry: sphere(20 30 40); /*or something*/
    material-type: phong;
    material-opacity: 0.5;
    material-color: red;
    diffuse-map: url(path/to/texture.jpg);
    bump-map: url(path/to/bumps.jpg);
    /* or similar, etc */
  }

  @keyframes {...} /*animate 3D styles!*/
</style>
```

Maybe `<model>` comes first, then eventually we make it have a shadow root once we have the primitives for it, much like how back in the day we could not see the shadow root of an `<input>` in devtools.

**Comment by zachernuk** [comment]
@trusktr My aim is to _initially_ introduce model as a black-box element, and work from there towards the capability set required by the more elaborate usage that authors are looking for beyond that.

In terms of polyfilling, I do believe that in a monoscopic / untracked context, it's totally possible to use WebGL/webGPU as a stand-in for correct <model> rendering. My priority has to identify the areas where that isn't adequate, e.g. visionOS / Meta Quest browser etc.
